title: "Jabed's Blog"
author: "Jabed Miah"
description: "The meanderings of a man obsessed with data science and programming." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "jabedmiah05@gmail.com"
github_username: "miahj1"
linkedin_username: "miahj1"
#twitter_username: "twitteruser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

show_excerpts: false

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
